### ISSUE TITLE
Switch to a more usable list.txt format and support more functionality?

### ISSUE THREAD

**Issue by FabianBartl** [IAmParadox27/jellyfin-plugin-media-bar#33]
*I don't know how independent this fork is, and whether I should open the issue here or in the forked repo. But here it is:*

I don't like the format used because:
 
- the name of the playlist has no purpose
- when you edit the list later, you don't know which movies the item IDs belong to unless you test them one by one
- no comments are supported

I suggest using a standard format like YAML as it supports the following features:

- Comments, so you can write the title after the element ID
- ordered lists
- objects to wrap the lists and assign more details
- multiple lists can be defined
- a separate entry could indicate which list is active instead of specifying a different file
- conditional selection of the playlist (would be an additional nice feature)

Example:
```yaml
active_playlists:
  - name: "Trillers"
    age_rating: 16              # if the permitted age rating of the individual user is higher or the same
    between: 22:00 - 03:00      # and it is currently between 22:00 and 3:00, this playlist will be selected

  - name: "Featured Movies"     # no condition, so it will be selected if none of the previous conditions are met

  - name: "all"                 # no condition, but it is not selected because the previous one is already selected


playlists:
  - name: "Featured Movies"
    sort_by: "name"                        # possible values: "random", "year", null
    sort_ascending: true                   # sorting order, descending when false
    item_ids:
      - c8d5976a20521b1ec16f9ee194a8af21   # spiderman
      - 2572c06ee4bf3e3fbbbaaab1184d76c8   # out of rosenheim
      - 18463206e2ec10d3a8ec9ad532a3226f   # codename uncle
  
  - name: "Thrillers"
    sort_by: "year"
    sort_ascending: true
    item_ids:
      - d43aef1908f470bb4b54148bdea142eb   # the shining
      - 04d97039fca66f5e09adaf28d293fa4d   # 7500
      - 6acb63ee9c47432408fc0dbcb05a470c   # se7en
  
  - name: "all"
    sort_by: "random"
    item_ids: "all"
```

The `item_ids: "all"` is already kind of a dynamic playlist. But defining a real dynamic playlists object would be really cool too, so one can set filters to select by genre, year, etc.

```yaml
playlist:
  - name: "All thrillers of the 90s"
    sort_by: "name"
    items:
      - type: "dynamic"       # the normal mode would be "list"
        from_year: 1990
        to_year: 1999
        genres: "thriller"
```
